name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 👈 Updated to v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'  # 👈 Added caching for faster builds

    - name: Install dependencies
      run: |
        npm ci         # 👈 Using 'ci' instead of 'install' for reproducible builds
        npm run build  # 👈 Add if you have a build step
      working-directory: ./backend

    - name: Create deployment package
      run: |
        mkdir -p deployment
        cp -r package.json package-lock.json server.js .env deployment/
        cp -r node_modules deployment/
        cp -r public deployment/  # 👈 If you have static files
      working-directory: ./backend

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'EventHorizon'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./backend/deployment  # 👈 Deploying the prepared package