name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Using LTS version for better compatibility
        cache: 'npm'

    - name: Install dependencies
      working-directory: ./backend
      run: |
        npm ci
        # Optional: Run security audit
        npm audit fix || true

    - name: Create deployment package
      working-directory: ./backend
      run: |
        # Create deployment folder
        mkdir -p deployment
        
        # Copy essential files
        cp package.json package-lock.json server.js deployment/
        
        # Copy environment variables if they exist
        if [ -f .env ]; then
          cp .env deployment/
          echo ".env copied to deployment"
        else
          echo "Warning: .env file not found"
        fi
        
        # Copy public folder if it exists
        if [ -d public ]; then
          cp -R public deployment/
          echo "public folder copied to deployment"
        fi
        
        # Install production dependencies only
        npm ci --production --prefix deployment
        
        echo "Deployment package created successfully"
        ls -la deployment/

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'EventHorizon'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./backend/deployment