name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # 👈 Downgraded to Node 18 for compatibility
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      working-directory: ./backend

    - name: Create deployment package
      run: |
        mkdir -p deployment
        cp -r package.json package-lock.json server.js .env deployment/
        cp -r node_modules deployment/
        [ -d public ] && cp -r public deployment/  # 👈 Only copy if 'public' exists
      working-directory: ./backend

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'EventHorizon'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./backend/deployment